
__version__ = "1.0.0"
__title__ = "general_utils"
__description__ = "Universal shared misc / helper / utils functions"
__uri__ = "http://solargis.com"
__doc__ = __description__ + " <" + __uri__ + ">"
__author__ = "Milos Korenciak"
__email__ = "milos.korenciak@solargis.com"
__license__ = "Proprietary"
__copyright__ = "Copyright (c) 2017 Solargis s.r.o."
